# Generated by Django 2.2.4 on 2019-10-03 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50)),
                ('hospitaladdress', models.CharField(max_length=50)),
                ('hospitalemail', models.EmailField(max_length=25)),
                ('hospitalpassword', models.CharField(max_length=10)),
                ('hospitalnumber', models.IntegerField(max_length=10)),
                ('hospitalpan', models.IntegerField(max_length=10)),
                ('login_date', models.DateField(default=datetime.date(2019, 10, 3))),
                ('hospitalprofile', models.ImageField(upload_to='image')),
            ],
        ),
    ]
