# Generated by Django 2.2.4 on 2019-10-03 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalprofile',
            field=models.ImageField(upload_to='uploadimage'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='login_date',
            field=models.DateField(verbose_name=datetime.date(2019, 10, 3)),
        ),
    ]
