# Generated by Django 2.2.4 on 2019-10-03 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20191003_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='login_date',
            field=models.DateField(default=datetime.date(2019, 10, 3)),
        ),
    ]
