# Generated by Django 2.2.4 on 2019-10-04 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20191003_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalprofile',
            field=models.ImageField(upload_to='hospitalimage'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='login_date',
            field=models.DateField(default=datetime.date(2019, 10, 4)),
        ),
    ]
