# Generated by Django 2.2.4 on 2019-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20191014_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospitalactivity',
            field=models.CharField(default='blank', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospitalmeme',
            field=models.ImageField(default='blank', upload_to='hospitalmeme'),
        ),
    ]
