# Generated by Django 2.2.4 on 2019-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_auto_20191211_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalactivity',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospitalmeme',
            field=models.ImageField(default=' ', upload_to='hospitalmeme'),
        ),
    ]
