# Generated by Django 2.2.4 on 2019-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_auto_20191212_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalactivity',
            field=models.CharField(default='blank', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospitalmeme',
            field=models.ImageField(default='blank', upload_to='hospitalmeme'),
        ),
    ]
