# Generated by Django 2.2.4 on 2019-12-19 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_auto_20191216_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('postid', models.IntegerField()),
                ('useractivity', models.CharField(default='blank', max_length=1000)),
                ('meme', models.ImageField(default='blank', upload_to='meme')),
                ('uploaddate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospitalactivity',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospitalmeme',
        ),
    ]
