# Generated by Django 2.2.4 on 2019-12-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_auto_20191219_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalactivity',
            name='hospitalprofile',
            field=models.ImageField(default=1, upload_to='hospitalimage'),
            preserve_default=False,
        ),
    ]
