# Generated by Django 2.2.4 on 2019-10-04 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorfirstname', models.CharField(max_length=50)),
                ('doctorlastname', models.CharField(max_length=50)),
                ('doctoraddress', models.CharField(max_length=50)),
                ('doctoremail', models.EmailField(max_length=25)),
                ('doctorpassword', models.CharField(max_length=10)),
                ('doctornumber', models.IntegerField()),
                ('doctorliscence', models.IntegerField()),
                ('login_date', models.DateField(default=datetime.date(2019, 10, 4))),
                ('doctorprofile', models.ImageField(upload_to='doctorimage')),
            ],
        ),
    ]
