# Generated by Django 2.2.4 on 2019-10-14 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='login_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
