# Generated by Django 2.2.4 on 2019-12-20 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20191014_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctoractivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('postid', models.IntegerField()),
                ('useractivity', models.CharField(default='blank', max_length=1000)),
                ('meme', models.ImageField(default='blank', upload_to='meme')),
                ('uploaddate', models.DateField(default=datetime.date.today)),
                ('doctorprofile', models.ImageField(upload_to='doctorimage')),
            ],
        ),
    ]
